export const MarkdownComponentName = 'markdown-component'
export const MarkdownBlockName = 'markdown-block'
export const MathjaxComponentName = 'mathjax-component'
export const MathjaxBlockName = 'mathjax-block'
export const TikzBlockName = 'tikz-block'
export const TikzComponentName = 'tikz-component'
